DROP TABLE IF EXISTS CITY;
CREATE TABLE CITY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  line1 VARCHAR(100) NOT NULL,
  line2 VARCHAR(100) NOT NULL,
  postalcode VARCHAR(10) DEFAULT NULL,
  city_id INT ,
  cuntry VARCHAR(50) NOT NULL,
  FOREIGN KEY (city_id) REFERENCES city(id)
);

DROP TABLE IF EXISTS person;
CREATE TABLE PERSON (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(10) ,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  address_id INT ,
  FOREIGN KEY (address_id) REFERENCES ADDRESS(id)
);

DROP TABLE IF EXISTS CHILD;
CREATE TABLE CHILD (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  age INT  NOT NULL,
  gender VARCHAR(10) NOT NULL,
  person_id INT  ,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (person_id) REFERENCES PERSON(id)
);